server:
  port: 8080
  
spring.cloud.stream.kafka.binder.brokers: 172.17.0.14:9092
spring.cloud.stream.kafka.consumer.properties.spring.json.use.type.headers: false
spring.cloud.stream.kafka.producer.properties.spring.json.use.type.headers: false

spring.cloud.stream:
  function:
    definition: orderEventPublisher;paymentEventConsumer;historyEventPublisher
  bindings:
    orderEventPublisher-out-0:
      destination: order-events
    paymentEventConsumer-in-0:
      destination: payment-events
    historyEventPublisher-out-0:
      destination: history-events
