server:
  port: 8080
  
spring.cloud.stream.kafka.binder.brokers: ${KAFKA_SERVICE_HOST}:9092

spring.cloud.stream:
  function:
    definition: orderEventPublisher;paymentEventConsumer;historyEventPublisher
  bindings:
    orderEventPublisher-out-0:
      destination: order-events
    paymentEventConsumer-in-0:
      destination: payment-events
    historyEventPublisher-out-0:
      destination: history-events
